[package]
name = "cancomms"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-std = "1.13"
bytes = "1.7.2"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3.30"
libc = "0.2.159"
socketcan = { version = "3.3.0", features = ["async-std"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
